### ISSUE TITLE
Creation of the association of Contact with the Company

### ISSUE THREAD

**Issue by Yegorov** [HubSpot/hubspot-api-ruby#187] opened 2022-11-24 21:15 UTC
How create association?
From [documentation](https://developers.hubspot.com/docs/api/crm/contacts), i do the following:

```ruby
api_client = Hubspot::Client.new(access_token: 'my_access_token')
api_response = api_client.crm.contacts.associations_api.create(
  contact_id: "335751", 
  to_object_type: "company", 
  to_object_id: "9613524891", 
  association_type: "contact_to_company"
)

ETHON: performed EASY effective_url=https://api.hubapi.com/crm/v4/objects/contacts/335751/associations/company/9613524891 response_code=400 return_code=ok total_time=0.477617
```

And get error:
```
Response body: {"status":"error","message":"Invalid JSON input: a request body was expected, but none found","correlationId":"a8c46543-cf49-460a-b807-c7eec1fb2edd","category":"VALIDATION_ERROR"}
```

**Comment by SerjKorchma** [comment] 2022-11-26 00:57
I have the same issue

**Comment by KillWolf** [comment] 2022-11-29 13:04
Same.

**Comment by mattwalters** [comment] 2022-11-29 20:01
I am having the same issue with `deal_to_contact`. It seems that creating any type of association is broken.

**Comment by mattwalters** [comment] 2022-11-29 21:11
If it is helpful for anyone, I was able to find this ugly work around:
```
module Hubspot
  module Discovery
    module Crm
      module Deals
        class AssociationsApi
          def call_api(api_method, params_to_pass)
            params_to_pass[-1][:debug_body] ||= [ ] if api_method == :create
            super
          end
        end
      end
    end
  end
end
```

It seems that the issue is that a default value is not supplied here: https://github.com/HubSpot/hubspot-api-ruby/blob/ab39076ae783f1bde50c8be6f4f2618ff2465272/lib/hubspot/codegen/crm/deals/api/associations_api.rb#L77-L78

I have not dug into this enough to understand why this key is `debug_body` instead of just `body`. The fix here may be as simple as adding a default `[]`.

**Comment by gkorban** [comment] 2022-11-29 22:57
It seems the create method expects an array of association types in the body of the request.

More info:
https://github.com/HubSpot/hubspot-api-ruby/pull/189#issuecomment-1331421425

**Comment by alzheltkovskiy-hubspot** [comment] 2022-12-08 11:08
Hi everyone
Could you check the [latest version](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v16.0.4), please?

**Comment by alzheltkovskiy-hubspot** [comment] 2022-12-15 14:33
Hi @Yegorov 
We are working on it. It should be fixed soon
Thank you.

**Comment by alzheltkovskiy-hubspot** [comment] 2023-01-04 09:12
Hi everyone.
Thank you for your participation.
Could you check the latest [version](https://github.com/HubSpot/hubspot-api-ruby/tree/v16.1.1)?

**Closed** 2023-01-06 08:50 UTC
